--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 12/8/2023 7:23:22 PM
-- Server version: 10.5.23
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE volunteer_engagement;

--
-- Drop table `comment`
--
DROP TABLE IF EXISTS comment;

--
-- Drop table `eventlike`
--
DROP TABLE IF EXISTS eventlike;

--
-- Drop table `eventregist`
--
DROP TABLE IF EXISTS eventregist;

--
-- Drop table `eventresponse`
--
DROP TABLE IF EXISTS eventresponse;

--
-- Drop table `event`
--
DROP TABLE IF EXISTS event;

--
-- Drop table `forhelprequest`
--
DROP TABLE IF EXISTS forhelprequest;

--
-- Drop table `ismember`
--
DROP TABLE IF EXISTS ismember;

--
-- Drop table `joinrequest`
--
DROP TABLE IF EXISTS joinrequest;

--
-- Drop table `statisticalreport`
--
DROP TABLE IF EXISTS statisticalreport;

--
-- Drop table `charityorganization`
--
DROP TABLE IF EXISTS charityorganization;

--
-- Drop table `volunteer`
--
DROP TABLE IF EXISTS volunteer;

--
-- Drop table `user`
--
DROP TABLE IF EXISTS user;

--
-- Drop table `role`
--
DROP TABLE IF EXISTS role;

--
-- Set default database
--
USE volunteer_engagement;

--
-- Create table `role`
--
CREATE TABLE role (
  id char(36) NOT NULL,
  name varchar(100) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `user`
--
CREATE TABLE user (
  id char(36) NOT NULL,
  name varchar(100) NOT NULL,
  username varchar(255) NOT NULL,
  password varchar(255) NOT NULL,
  active tinyint(4) NOT NULL,
  phone varchar(15) NOT NULL,
  email varchar(255) DEFAULT NULL,
  address varchar(255) NOT NULL,
  role_id char(36) NOT NULL,
  status tinyint(4) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 8192,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE user
ADD CONSTRAINT user_ibfk_1 FOREIGN KEY (role_id)
REFERENCES role (id);

--
-- Create table `volunteer`
--
CREATE TABLE volunteer (
  id char(36) NOT NULL,
  user_id char(36) NOT NULL,
  support_time datetime NOT NULL,
  location varchar(255) NOT NULL,
  skills varchar(255) NOT NULL,
  is_delete enum ('0', '1') NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE volunteer
ADD CONSTRAINT volunteer_ibfk_1 FOREIGN KEY (user_id)
REFERENCES user (id);

--
-- Create table `charityorganization`
--
CREATE TABLE charityorganization (
  id char(36) NOT NULL,
  user_id char(36) NOT NULL,
  establish_date date NOT NULL,
  fax varchar(15) NOT NULL,
  website varchar(255) NOT NULL,
  description text NOT NULL,
  volunteer_id varchar(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE charityorganization
ADD CONSTRAINT charityorganization_ibfk_1 FOREIGN KEY (user_id)
REFERENCES user (id);

--
-- Create table `statisticalreport`
--
CREATE TABLE statisticalreport (
  id char(36) NOT NULL,
  organization_id char(36) NOT NULL,
  time enum ('tháng', 'quý', 'n?m') NOT NULL,
  content varchar(255) NOT NULL,
  date date NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE statisticalreport
ADD CONSTRAINT statisticalreport_ibfk_1 FOREIGN KEY (organization_id)
REFERENCES charityorganization (id);

--
-- Create table `joinrequest`
--
CREATE TABLE joinrequest (
  id char(36) NOT NULL,
  status enum ('initial', 'approved', 'rejected') NOT NULL,
  user_id char(36) NOT NULL,
  support_time datetime NOT NULL,
  location varchar(255) NOT NULL,
  skills varchar(255) NOT NULL,
  organization_id char(36) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE joinrequest
ADD CONSTRAINT joinrequest_ibfk_1 FOREIGN KEY (user_id)
REFERENCES user (id);

--
-- Create foreign key
--
ALTER TABLE joinrequest
ADD CONSTRAINT joinrequest_ibfk_2 FOREIGN KEY (organization_id)
REFERENCES charityorganization (id);

--
-- Create table `ismember`
--
CREATE TABLE ismember (
  id char(36) NOT NULL,
  volunteer_id char(36) NOT NULL,
  organization_id char(36) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE ismember
ADD CONSTRAINT ismember_ibfk_1 FOREIGN KEY (volunteer_id)
REFERENCES volunteer (id);

--
-- Create foreign key
--
ALTER TABLE ismember
ADD CONSTRAINT ismember_ibfk_2 FOREIGN KEY (organization_id)
REFERENCES charityorganization (id);

--
-- Create table `forhelprequest`
--
CREATE TABLE forhelprequest (
  id char(36) NOT NULL,
  description varchar(255) NOT NULL,
  date date NOT NULL,
  status int(11) NOT NULL COMMENT 'initial = ''0'', approved = ''1'', rejected = ''2''',
  user_id char(36) NOT NULL,
  organization_id char(36) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE forhelprequest
ADD CONSTRAINT forhelprequest_ibfk_1 FOREIGN KEY (user_id)
REFERENCES user (id);

--
-- Create foreign key
--
ALTER TABLE forhelprequest
ADD CONSTRAINT forhelprequest_ibfk_2 FOREIGN KEY (organization_id)
REFERENCES charityorganization (id);

--
-- Create table `event`
--
CREATE TABLE event (
  id char(36) NOT NULL,
  title varchar(255) NOT NULL,
  content longtext NOT NULL,
  image varchar(255) NOT NULL,
  created_date date NOT NULL,
  modified_date date NOT NULL,
  like_count int(11) NOT NULL DEFAULT 0,
  organization_id char(36) NOT NULL,
  text text NOT NULL,
  comment_count int(11) NOT NULL DEFAULT 0,
  status int(11) NOT NULL COMMENT 'initial = 0, approved = 1, rejected = 2',
  time datetime NOT NULL,
  review longtext NOT NULL,
  type int(11) NOT NULL COMMENT '0, 1',
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 32768,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE event
ADD CONSTRAINT event_ibfk_1 FOREIGN KEY (organization_id)
REFERENCES charityorganization (id);

--
-- Create table `eventresponse`
--
CREATE TABLE eventresponse (
  id char(36) NOT NULL,
  user_id char(36) NOT NULL,
  event_id char(36) NOT NULL,
  response_content text NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE eventresponse
ADD CONSTRAINT eventresponse_ibfk_1 FOREIGN KEY (user_id)
REFERENCES user (id);

--
-- Create foreign key
--
ALTER TABLE eventresponse
ADD CONSTRAINT eventresponse_ibfk_2 FOREIGN KEY (event_id)
REFERENCES event (id);

--
-- Create table `eventregist`
--
CREATE TABLE eventregist (
  id char(36) NOT NULL,
  event_id char(36) NOT NULL,
  volunteer_id char(36) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE eventregist
ADD CONSTRAINT eventregist_ibfk_1 FOREIGN KEY (event_id)
REFERENCES event (id);

--
-- Create foreign key
--
ALTER TABLE eventregist
ADD CONSTRAINT eventregist_ibfk_2 FOREIGN KEY (volunteer_id)
REFERENCES volunteer (id);

--
-- Create table `eventlike`
--
CREATE TABLE eventlike (
  id char(36) NOT NULL,
  user_id char(36) NOT NULL,
  event_id char(36) NOT NULL,
  response_content text NOT NULL,
  status tinyint(4) NOT NULL,
  time datetime NOT NULL,
  upvote int(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE eventlike
ADD CONSTRAINT eventlike_ibfk_1 FOREIGN KEY (user_id)
REFERENCES user (id);

--
-- Create foreign key
--
ALTER TABLE eventlike
ADD CONSTRAINT eventlike_ibfk_2 FOREIGN KEY (event_id)
REFERENCES event (id);

--
-- Create table `comment`
--
CREATE TABLE comment (
  id char(36) NOT NULL,
  event_id char(36) NOT NULL,
  user_id char(36) NOT NULL,
  text text NOT NULL,
  video varchar(255) DEFAULT NULL,
  time datetime NOT NULL,
  status tinyint(4) NOT NULL,
  picture varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE comment
ADD CONSTRAINT comment_ibfk_1 FOREIGN KEY (event_id)
REFERENCES event (id);

--
-- Create foreign key
--
ALTER TABLE comment
ADD CONSTRAINT comment_ibfk_2 FOREIGN KEY (user_id)
REFERENCES user (id);

-- 
-- Dumping data for table role
--
INSERT INTO role VALUES
('79ec49f7-9382-11ee-a40d-d45d64601179', 'Admin');

-- 
-- Dumping data for table user
--
INSERT INTO user VALUES
('7304af8b-d6a6-4d58-a581-4026d18d164e', 'matkhau123456', 'test', '$2a$11$I91vlFF93gIBDpguZAW5yeKvS2SFXh36IstEg2MtrW4R4MXZs.MlC', 0, 'string', 'string', 'string', '79ec49f7-9382-11ee-a40d-d45d64601179', 0),
('d77b66da-9384-11ee-a40d-d45d64601179', 'string', 'string', '$2a$11$gKl3UwUQmcKTrn3j0A4BHuvMVAU7ZV3j.X2x5aW8YJPXYGM2j.dIK', 0, 'string', 'string', 'string', '79ec49f7-9382-11ee-a40d-d45d64601179', 0);

-- 
-- Dumping data for table charityorganization
--
INSERT INTO charityorganization VALUES
('2882413a-9421-11ee-a40d-d45d64601179', '7304af8b-d6a6-4d58-a581-4026d18d164e', '2023-12-06', '', '', '', '');

-- 
-- Dumping data for table volunteer
--
-- Table volunteer_engagement.volunteer does not contain any data (it is empty)

-- 
-- Dumping data for table event
--
INSERT INTO event VALUES
('b25a41f5-a65c-49de-a842-2b6c07b5a5a6', 'string', 'string', 'string', '2023-12-08', '2023-12-08', 0, '2882413a-9421-11ee-a40d-d45d64601179', 'string', 0, 0, '2023-12-08 12:19:39', 'string', 0);

-- 
-- Dumping data for table statisticalreport
--
-- Table volunteer_engagement.statisticalreport does not contain any data (it is empty)

-- 
-- Dumping data for table joinrequest
--
-- Table volunteer_engagement.joinrequest does not contain any data (it is empty)

-- 
-- Dumping data for table ismember
--
-- Table volunteer_engagement.ismember does not contain any data (it is empty)

-- 
-- Dumping data for table forhelprequest
--
INSERT INTO forhelprequest VALUES
('76d087cc-60ba-467c-abda-b9b006ff0390', 'string', '2023-12-06', 0, '7304af8b-d6a6-4d58-a581-4026d18d164e', '2882413a-9421-11ee-a40d-d45d64601179');

-- 
-- Dumping data for table eventresponse
--
-- Table volunteer_engagement.eventresponse does not contain any data (it is empty)

-- 
-- Dumping data for table eventregist
--
-- Table volunteer_engagement.eventregist does not contain any data (it is empty)

-- 
-- Dumping data for table eventlike
--
-- Table volunteer_engagement.eventlike does not contain any data (it is empty)

-- 
-- Dumping data for table comment
--
-- Table volunteer_engagement.comment does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;